---
title: "Jornadas IIFAP 2024"
author: "JPC"
date: "`r Sys.Date()`"
output: html_document
---

## Desarrollo de estrategias metodológicas para la determinación del precio de los inmuebles edificados en el área metropolitana de la Ciudad de Córdoba utilizando técnicas de aprendizaje computacional y estadística espacial.


### Objetivos generales:

Desarrollar estrategias metodológicas para la determinación del precio de los inmuebles edificados en el área metropolitana de la Ciudad de Córdoba utilizando datos abiertos, técnicas de aprendizaje computacional y estadística espacial.

### Objetivos específicos:

* OE1: Conformar una muestra de inmuebles edificados en venta o vendidos para conocer la
distribución espacial de los precios de mercado.

* OE2: Identificar y construir variables territoriales consideradas determinantes en la
formación de precios de los inmuebles construidos.

* OE3: Predecir el precio por metro cuadrado de los inmuebles edificados en el área
metropolitana de Córdoba.

* OE4: Identificar el impacto de diferentes variables territoriales en la conformación del
precio por metro cuadrado de los inmuebles edificados.

* OE5: Validar la potencialidad de transferencia del proceso metodológico y sus resultados
para su implementación como herramienta para el diseño de políticas públicas.

### Equipo:





### Avances:



```{r, include=T, echo=F, fig.align='center'}
load("base_de_datos_completa_2024-09-11.Rda")
mapview::mapview(datos, zcol = "pm2", at = quantile(datos$pm2, probs = seq(0,1,0.2)))
```

